"""Adicionar tabela de usuários

Revision ID: create_user_table
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'create_user_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USUARIO',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USERNAME', sa.String(length=50), nullable=False),
    sa.Column('PASSWORD_HASH', sa.String(length=255), nullable=False),
    sa.Column('EMAIL', sa.String(length=100), nullable=True),
    sa.Column('IS_ACTIVE', sa.Boolean(), nullable=False),
    sa.Column('CRIADO_EM', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ATUALIZADO_EM', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_USUARIO_ID'), 'USUARIO', ['ID'], unique=False)
    op.create_index(op.f('ix_USUARIO_USERNAME'), 'USUARIO', ['USERNAME'], unique=True)
    op.create_index(op.f('ix_USUARIO_EMAIL'), 'USUARIO', ['EMAIL'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_USUARIO_EMAIL'), table_name='USUARIO')
    op.drop_index(op.f('ix_USUARIO_USERNAME'), table_name='USUARIO')
    op.drop_index(op.f('ix_USUARIO_ID'), table_name='USUARIO')
    op.drop_table('USUARIO')
    # ### end Alembic commands ###